version: '3.5'

services:
  django:
    build:
      context: ./backend/django_backend/
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_backend:/app
    working_dir: /app
    environment:
      - .dev.env
    networks:
      - django_db_network
    depends_on:
      db:
        condition: service_healthy
 #To persist the data beyond the life of the container we configured a volume.
 #This config will bind postgres_data to the "/var/lib/postgresql/data/" directory in the container.
  db:
    build:
      context: ./backend/database/
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - django_db_network
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

#custom networks to facilitate communication between the containers
networks:
  django_db_network:
    name: django_db_network