# Generated by Django 5.0.4 on 2024-06-10 14:55

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_avatar_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to),
        ),
    ]
