# Generated by Django 5.0.4 on 2024-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(),
        ),
    ]
