MAP_WIDTH: int = 200
MAP_HEIGHT: int = 150

PLAYER_HEIGHT: int = 15
PLAYER_WIDTH: int = 5
PLAYER_DEPTH: int = 2

PLAYER1_START_X: int = 10
PLAYER1_START_Y: int = 75
PLAYER1_START_Z: int = 0

PLAYER2_START_X: int = 190
PLAYER2_START_Y: int = 75
PLAYER2_START_Z: int = 0

BALL_START_X: int = 100
BALL_START_Y: int = 75
BALL_START_DX: int = 1
BALL_START_DY: int = 1
