MAP_WIDTH: int = 200
MAP_HEIGHT: int = 150

PLAYER_HEIGHT: int = 3

PLAYER1_START_X: int = -70
PLAYER1_START_Y: int = 0
PLAYER1_START_Z: int = 0

PLAYER2_START_X: int = 70
PLAYER2_START_Y: int = 0
PLAYER2_START_Z: int = 0

BALL_START_X: int = 0
BALL_START_Y: int = 0
BALL_START_DX: int = 1
BALL_START_DY: int = 1
