MAP_WIDTH: int = 250
MAP_HEIGHT: int = 150

PLAYER_HEIGHT: int = 3

PLAYER1_START_X: int = 1
PLAYER1_START_Y: int = MAP_HEIGHT // 2

PLAYER2_START_X: int = MAP_WIDTH - 2
PLAYER2_START_Y: int = MAP_HEIGHT // 2

BALL_START_X: int = MAP_WIDTH // 2
BALL_START_Y: int = MAP_HEIGHT // 2
BALL_START_DIR_X: int = 1
BALL_START_DIR_Y: int = 1
